# Generated by Django 4.0.1 on 2022-02-02 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_author_reg_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=64, verbose_name='Header')),
                ('text', models.TextField(verbose_name='Post text')),
                ('is_active', models.BooleanField(default=False, verbose_name='Is active')),
                ('reg_date', models.DateField(auto_now_add=True)),
                ('author', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='post.author')),
            ],
            options={
                'db_table': 'posts',
            },
        ),
    ]
