# Generated by Django 4.0.1 on 2022-02-02 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_categories_post_category'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='categories',
            table='categories',
        ),
    ]
