# Generated by Django 4.0.1 on 2022-02-08 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_post_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='nickname',
            field=models.CharField(max_length=8, unique=True, verbose_name='Nickname'),
        ),
    ]
